CREATE DATABASE empleadosnn;
USE empleadosnn;

CREATE TABLE DPTO
(COD_DPTO VARCHAR(4),
NOMBRE VARCHAR(50)) ENGINE=InnoDB;

CREATE TABLE EMPLE
(DNI VARCHAR(9),
SALARIO DOUBLE,
FECHA_NAC DATE) ENGINE=InnoDB;

ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY(COD_DPTO);
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY(DNI);

CREATE TABLE EMPLE_DPTO
(COD_DPTO VARCHAR(40),
DNI VARCHAR(9),
FECHA_INICIO DATE,
FECHA_FIN DATE) ENGINE=InnoDB;

ALTER TABLE EMPLE_DPTO ADD CONSTRAINT PK_EMPLE_DPTO PRIMARY KEY(COD_DPTO,DNI);

ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DPTO
FOREIGN KEY (COD_DPTO) REFERENCES DPTO(COD_DPTO);

ALTER TABLE EMPLE_DPTO ADD CONSTRAINT FK_EMPLE_DNI
FOREIGN KEY (DNI) REFERENCES EMPLE(DNI);


INSERT INTO EMPLE_DPTO (COD_DPTO,DNI,FECHA_INICIO,FECHA_FIN) VALUES
("111A","342342K","2000-01-01","2000-01-02");