/* Modelo Logico empleado - departamento

cardinalidad 1:N*/

CREATE DATABASE empleados1n;

USE empleados1n;

CREATE TABLE DPTO
(COD_DPTO VARCHAR(4),
NOMBRE VARCHAR(40));

CREATE TABLE EMPLE
(DNI VARCHAR(9),
NOMBRE VARCHAR(40),
SALARIO DOUBLE,
FECHA_NAC DATE,
COD_DPTO VARCHAR(4));


ALTER TABLE DPTO ADD CONSTRAINT PK_DPTO PRIMARY KEY(COD_DPTO);
ALTER TABLE EMPLE ADD CONSTRAINT PK_EMPLE PRIMARY KEY(DNI);
ALTER TABLE EMPLE ADD CONSTRAINT FK_DPTO_EMPLE_COD_DPTO
FOREIGN KEY (COD_DPTO) REFERENCES DPTO(COD_DPTO);

INSERT INTO DPT (COD_DPTO,NOMBRE) VALUES ("D001","CONTABILIDAD");
INSERT INTO DPT (COD_DPTO,NOMBRE) VALUES ("D002","NOMINAS");
INSERT INTO DPT (COD_DPTO,NOMBRE) VALUES ("D003","FINANZAS");

INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES
("1111111A","ANA","2000","2000-01-01","D001");
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES
("1111111B","JHON","2000","2000-02-01","D002");
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES
("1111111C","JUAN","2000","2000-03-01","D003");
INSERT INTO EMPLE (DNI,NOMBRE,SALARIO,FECHA_NAC,COD_DPTO) VALUES
("1111111D","LUIS","2000","2000-04-01","D004");